name: CD - Deploy (Self-Hosted)

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: self-hosted # <<<< ใช้ runner บนเครื่องคุณ
    permissions:
      contents: read
      packages: read
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository }}/portfolio:latest
      COMPOSE_PROFILE: prod # เปลี่ยนเป็น dev หากต้องการ
      PROJECT_DIR: E:\project\portfolio # <<< แก้ให้ตรงเครื่องคุณ
    steps:
      - uses: actions/checkout@v4

      - name: Docker login GHCR
        shell: powershell
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Pull image & compose up
        shell: powershell
        env:
          WEB_IMAGE: ${{ env.IMAGE_NAME }}
        run: |
          cd "$env:PROJECT_DIR"
          docker pull "$env:IMAGE_NAME"
          # ส่งตัวแปร WEB_IMAGE ให้ docker compose ผ่าน env ของ process
          $env:WEB_IMAGE = "${{ env.IMAGE_NAME }}"
          docker compose --profile $env:COMPOSE_PROFILE up -d
          docker image prune -f
