name: CD - Deploy to Server

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      packages: read
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository }}/boom-portfolio:latest
      REMOTE_DIR: /opt/boom-portfolio
      COMPOSE_PROFILE: prod
    steps:
      - name: Use SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Add Host
        run: ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} '
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            cd '"$REMOTE_DIR"' || exit 1
            docker pull '"$IMAGE_NAME"'
            export DOCKER_TARGET=prod
            export WEB_IMAGE='"$IMAGE_NAME"'
            docker compose --profile '"$COMPOSE_PROFILE"' up -d --build
            docker system prune -f
          '
